<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/**
 * @var $block \Magento\Sales\Block\Order\Totals
 * @see \Magento\Sales\Block\Order\Totals
 */
?>
<?php foreach ($block->getTotals() as $_code => $_total) : ?>
    <?php
    if ($_code == 'discount') {
        $orderItems = $block->getSource()->getOrder()->getAllItems();
        $tierPriceDiscount = 0;
        foreach ($orderItems as $orderItem) {
            $tmp =  0;
            if ($orderItem->getTierPriceData()) {
                foreach (json_decode($orderItem->getTierPriceData(), true) as $tierPrice) {
                    if ($tierPrice['discount_percentage'] && ($tierPrice['discount_percentage'] > 0)) {
                        $tmp = ((int) $orderItem->getPrice() * $tierPrice['discount_percentage']) / 100;
                    } elseif ($tierPrice['discount_amount']) {
                        $tmp = $tierPrice['discount_amount'];
                    } else {
                        $tmp = 0;
                    }
                }
                $tierPriceDiscount += $tmp * $orderItem->getQtyTierPrice();
                $tierPriceDiscount = round($tierPriceDiscount);
            }
        }

        if ($_total->getValue() + $tierPriceDiscount == 0) {
            continue;
        } else {
            $_total->setValue($_total->getValue() + $tierPriceDiscount);
        }
    }
    ?>
    <?php if ($_total->getBlockName()) : ?>
        <?= $block->getChildHtml($_total->getBlockName(), false) ?>
    <?php else :?>
    <tr class="<?= $block->escapeHtmlAttr($_code) ?>">
        <th <?= /* @noEscape */ $block->getLabelProperties() ?> scope="row">
            <?php if ($_total->getStrong()) : ?>
                <strong><?= $block->escapeHtml($_total->getLabel()) ?></strong>
            <?php else : ?>
                <?= $block->escapeHtml($_total->getLabel()) ?>
            <?php endif ?>
        </th>
        <td <?= /* @noEscape */ $block->getValueProperties() ?> data-th="<?= $block->escapeHtmlAttr($_total->getLabel()) ?>">
            <?php if ($_total->getStrong()) : ?>
                <strong><?= /* @noEscape */ $block->formatValue($_total) ?></strong>
            <?php else : ?>
                <?= /* @noEscape */ $block->formatValue($_total) ?>
            <?php endif?>
        </td>
    </tr>
    <?php endif; ?>
<?php endforeach?>
