<script type="text/x-magento-template" id="tier-prices-template">
    <ul class="prices-tier items">
        <% var exclPrice = ' <span class="price-wrapper price-excluding-tax"'
            + 'data-label="<?= $block->escapeHtml(__('Excl. Tax')) ?>">'
            + '<span class="price">&nbsp;%1</span>'
            + '</span>'
        %>

        <% _.each(tierPrices, function(item, key) { %>
            <% var itemExclPrice = item.hasOwnProperty('excl_tax_price')
                ? exclPrice.replace('%1', priceUtils.formatPrice(item['excl_tax_price'], currencyFormat))
                : ''
            %>

            <% var priceStr = '<span class="price-container price-tier_price">'
                    + '<span data-price-amount="' + priceUtils.formatPrice(item.price, currencyFormat) + '"'
                    + ' data-price-type=""' + ' class="price-wrapper price-including-tax">'
                    + '<span class="price">' + priceUtils.formatPrice(item.price, currencyFormat) + '</span>'
                    + '</span>' + itemExclPrice + '</span>';
            %>
            <li class="item">
                <%= '<?= $block->escapeHtml(__('%1', '%1')) ?>'
                    .replace('%1', item.text)
                %>
            </li>
        <% }); %>
    </ul>
</script>
<div data-role="tier-price-block"></div>
